Produit_index:
    path:     /liste/{type}
    defaults: { _controller: "ProduitBundle:Produit:index" }

Produit_show:
    path:     /{id}/show
    defaults: { _controller: "ProduitBundle:Produit:show" }

Produit_new:
    path:     /new
    defaults: { _controller: "ProduitBundle:Produit:new" }

Produit_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProduitBundle:Produit:edit" }

Produit_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProduitBundle:Produit:delete" }

Produit_mesproduit:
    path:     /mesproduits
    defaults: { _controller: "ProduitBundle:Produit:mesproduits" }

Produit_indexback:
    path:     /indexback
    defaults: { _controller: "ProduitBundle:Produit:IndexBack" }

Produit_visibilite:
    path:     /{id}/vis
    defaults: { _controller: "ProduitBundle:Produit:visibilite" }

Produit_nbusers:
    path:     /nbr
    defaults: { _controller: "ProduitBundle:Produit:NombreUser" }

Produit_recherche:
    path:     /rech
    defaults: { _controller: "ProduitBundle:Produit:Recherche" }

Produit_stat:
    path:     /stat
    defaults: { _controller: "ProduitBundle:Statistique:StatProduitParCategorie" }









