event_index:
    path:     /listevent
    defaults: { _controller: "EvenementBundle:Evenement:index" }
    methods:  GET

event1_index:
    path:     /gridevent
    defaults: { _controller: "EvenementBundle:Evenement:index1" }
    methods:  GET



event_mesevenement:
    path:     /mesevenement
    defaults: { _controller: "EvenementBundle:Evenement:mesevenement" }
    methods:  GET


event_show:
    path:     /{id}/show
    defaults: { _controller: "EvenementBundle:Evenement:show" }
    methods:  GET

event_new:
    path:     /new
    defaults: { _controller: "EvenementBundle:Evenement:new" }
    methods:  [GET, POST]



event_edit:
    path:     /{id}/edit
    defaults: { _controller: "EvenementBundle:Evenement:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "EvenementBundle:Evenement:delete" }
    methods:  DELETE
