my_app_mail_homepage1:
    path:     /
    defaults: { _controller: MyAppMailBundle:Default:index }

my_app_mail_homepage:
    path: /send
    defaults: { _controller: MyAppMailBundle:Mail:index }


my_app_mail_accuse:
    path: /success
    defaults: { _controller: MyAppMailBundle:Mail:success }
