liste_annonce1:
    path:     /
    defaults: { _controller: "AnnonceBundle:Annonce:index1" }


recherche:
    path:     /
    defaults: { _controller: "AnnonceBundle:Annonce:annonces" }

voirProfile:
    path:     /{id}/voirProfil
    defaults: { _controller: "AnnonceBundle:Annonce:voirProfilUser" }


liste_annonce2:
    path:     /
    defaults: { _controller: "AnnonceBundle:Annonce:index2" }

Annonce_Par_type:
    path:     /liste/{type}
    defaults: { _controller: "AnnonceBundle:Annonce:AnnonceParType" }

affiche_annonce:
    path:     /{id}/affiche
    defaults: { _controller: "AnnonceBundle:Annonce:affiche" }

annonce_new:
    path:     /new
    defaults: { _controller: "AnnonceBundle:Annonce:proposer" }

annonce_edit:
    path:     /{id}/edit
    defaults: { _controller: "AnnonceBundle:Annonce:modifier" }

annonce_delete:
    path:     /{id}/delete
    defaults: { _controller: "AnnonceBundle:Annonce:DeleteAnnonce" }
Annonce_admin:
    path:     /Adannonce
    defaults: { _controller: "AnnonceBundle:Annonce:indexAdmin" }

MesAnnonce:
    path:     /mesAnnonce
    defaults: { _controller: "AnnonceBundle:Annonce:mesannonce" }

MesAnnonceinactive:
    path:     /mesAnnonceInactive
    defaults: { _controller: "AnnonceBundle:Annonce:mesannonceInactive" }

